### ISSUE TITLE
Error Closing Repository

### ISSUE THREAD

**Issue by techstuff1971** [leachim6/hello-world#1379] opened 2022-07-16 04:33 UTC
Hi, I just tried cloning the repository and got the following error:

`$ git clone https://github.com/leachim6/hello-world.git
Cloning into 'hello-world'...
remote: Enumerating objects: 7534, done.
remote: Counting objects: 100% (498/498), done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 7534 (delta 261), reused 360 (delta 152), pack-reused 7036
Receiving objects: 100% (7534/7534), 5.05 MiB | 2.76 MiB/s, done.
Resolving deltas: 100% (3890/3890), done.
error: invalid path '#/*><>'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

The hello-world directory was created but empty.  'git status' showed a bunch (all) of the files in deleted state.  I then tried:

` git restore --source=HEAD :/`

with the following result:

`error: invalid path '#/*><>'
error: invalid path '#/><>'
error: invalid path 'a/AnalF*ck.af'
error: invalid path 'l/Lost.???'
`

Obviously, some of this seems suspicious.  Am I doing something wrong (I'm pretty new to Git) or was the repository hacked?

**Comment by Richienb** [comment] 2022-07-16 04:34
Duplicate of https://github.com/leachim6/hello-world/issues/1354

**Closed by Richienb** 2022-07-16 04:34 UTC
